In [22]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.1'

In [3]:
pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head(10)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   
5                  190            3.0         NaN     2484.883986   
6                  240            7.0       127.0     3006.542287   
7                  150            4.0       239.0     3638.657780   
8                  250            1.0       174.0     2714.219310   
9                  150            4.0       123.0     3509.036569   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5          14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6          22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7          17.3        2020     USA    Diesel    All-wheel drive        1.0   
8          10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9          10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369  
5            17.271818  
6            13.210412  
7            12.848884  
8            16.823554  
9            12.298355

In [6]:
df["fuel_type"].nunique()

2

In [7]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df[df["origin"]=="Asia"]["fuel_efficiency_mpg"].max().round(2)

np.float64(23.76)

In [9]:
df["horsepower"].median()

np.float64(149.0)

In [10]:
df["horsepower"].mode()

0    152.0
Name: horsepower, dtype: float64

In [11]:
df["horsepower"] = df["horsepower"].fillna(152.0)

In [12]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0       152.0     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [13]:
df["horsepower"].isna()

0       False
1       False
2       False
3       False
4       False
        ...  
9699    False
9700    False
9701    False
9702    False
9703    False
Name: horsepower, Length: 9704, dtype: bool

In [14]:
df["horsepower"].median()

np.float64(152.0)

In [15]:
df["vehicle_weight"].sum()

np.float64(29124430.759692907)

In [16]:
asian_cars = df[df["origin"] == "Asia"]

In [27]:
asian_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [18]:
car_type = asian_cars[["vehicle_weight", "model_year"]]


In [28]:
car_type

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [29]:
X = car_type.to_numpy()

In [30]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       ...,
       [2545.07013932, 2012.        ],
       [3107.42781965, 2005.        ],
       [2908.04347736, 2005.        ]], shape=(3247, 2))

In [40]:
XTX = X.T.dot(X)

In [41]:
XTX

array([[3.01651358e+10, 1.96349896e+10],
       [1.96349896e+10, 1.31377985e+10]])

In [42]:
XTX_inv = np.linalg.inv(XTX)

In [43]:
XTX_inv

array([[ 1.21977675e-09, -1.82300740e-09],
       [-1.82300740e-09,  2.80067709e-09]])

In [44]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [45]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [46]:
a = XTX_inv.dot(X.T)

In [38]:
a

array([[-3.64441297e-07, -2.68546211e-07,  7.11302917e-07, ...,
        -5.63473493e-07,  1.35238384e-07, -1.07966002e-07],
       [ 6.98123134e-07,  5.54347218e-07, -9.10306654e-07, ...,
         9.95280615e-07, -4.95063361e-08,  3.13972795e-07]],
      shape=(2, 3247))

In [47]:
w = a.dot(y)

ValueError: shapes (2,3247) and (7,) not aligned: 3247 (dim 1) != 7 (dim 0)